name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GO111MODULE: "on"
  CGO_ENABLED: "0"
  GOARCH: "amd64"
  GOPRIVATE: "github.com/winchci"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - uses: actions/checkout@v2

    - uses: actions/cache@v1
      with:
        path: /home/runner/go/pkg/mod
        key: v1-go-mod-${{ hashFiles('go.sum') }}
        restore-keys: v1-go-mod-

    - name: Build winch
      run: |
        go mod download
        go test ./...

        go get -u \
            github.com/kisielk/errcheck \
            golang.org/x/tools/cmd/goimports \
            golang.org/x/lint/golint \
            github.com/securego/gosec/cmd/gosec \
            golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow \
            honnef.co/go/tools/cmd/staticcheck

        export GOOS=linux
        mkdir -p bin/$GOOS-$GOARCH

        go build -o bin/$GOOS-$GOARCH/winch ./cmd/winch/main.go
        go build -o bin/$GOOS-$GOARCH/winch-go-errcheck github.com/kisielk/errcheck
        go build -o bin/$GOOS-$GOARCH/winch-go-imports golang.org/x/tools/cmd/goimports
        go build -o bin/$GOOS-$GOARCH/winch-go-lint golang.org/x/lint/golint
        go build -o bin/$GOOS-$GOARCH/winch-go-sec github.com/securego/gosec/cmd/gosec
        go build -o bin/$GOOS-$GOARCH/winch-go-shadow golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow
        go build -o bin/$GOOS-$GOARCH/winch-go-staticcheck honnef.co/go/tools/cmd/staticcheck

        export GOOS=darwin
        mkdir -p bin/$GOOS-$GOARCH

        go build -o bin/$GOOS-$GOARCH/winch ./cmd/winch/main.go
        go build -o bin/$GOOS-$GOARCH/winch-go-errcheck github.com/kisielk/errcheck
        go build -o bin/$GOOS-$GOARCH/winch-go-imports golang.org/x/tools/cmd/goimports
        go build -o bin/$GOOS-$GOARCH/winch-go-lint golang.org/x/lint/golint
        go build -o bin/$GOOS-$GOARCH/winch-go-sec github.com/securego/gosec/cmd/gosec
        go build -o bin/$GOOS-$GOARCH/winch-go-shadow golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow
        go build -o bin/$GOOS-$GOARCH/winch-go-staticcheck honnef.co/go/tools/cmd/staticcheck

    - run: ./bin/linux/winch ci
