name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GO111MODULE: "on"
      CGO_ENABLED: "0"
      GOOS: "linux"
      GOPRIVATE: "github.com/winchci"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Check out code
      uses: actions/checkout@v2

    - name: Cache Go modules
      uses: actions/cache@v1
      with:
        path: /home/runner/go/pkg/mod
        key: v1-go-mod-${{ hashFiles('go.sum') }}
        restore-keys: v1-go-mod-

    - name: Cache Go build
      uses: actions/cache@v1
      with:
        path: /home/runner/.cache/go-build
        key: v1-go-build-${{ hashFiles('go.sum') }}
        restore-keys: v1-go-build-

    - name: Build winch
      run: |
        mkdir -p bin
        go mod download
        go test ./...
        go build -o bin/winch ./cmd/winch/main.go

    - name: Turn the handle
      run: |
        ./bin/winch ci
